### ISSUE TITLE
how to import to webstorm

### ISSUE THREAD

**Issue by kevinten10** [zxj5470/wxapp-intellij#1]
Looking forward to your product

**Comment by zxj5470** [comment]
see release.
https://github.com/zxj5470/wxapp-intellij/releases
如果需要智能提示微信的 js API 可以看另一个项目 wx.d.ts 。添加 d.ts 作为 library。在设置里面搜索libraries然后添加。

**Comment by aojie654** [comment]
@zxj5470 请问您是使用idea进行微信小程序开发的吗? 如何使用webstorm进行导入呢?

**Comment by zxj5470** [comment]
@aojie654 加载插件……下载 [wxapp-intellij.jar](https://github.com/zxj5470/wxapp-intellij/releases/download/0.1.0/wxapp-intellij.jar) 了以后
去设置里面的plugin点加载本地包 或者 直接在运行的webstorm里面把插件文件 【拖进编辑面板的部分】就可以了。

然后如果之前有绑定过.wxml和.wxss的文件类型为html和css的话需要重新绑定一下文件类型为.wxml和.wxss。有空我考虑一下这周末把文档补上……

**Comment by qinalan** [comment]
您好, 我想请问下, 我导入进去后, wxss里的rpx还是不行, 没有智能提示, 也还飘红. 这是为什么呢?

**Comment by liunewshine** [comment]
![image](https://user-images.githubusercontent.com/7698511/55387813-b7305780-5564-11e9-8232-b01e5f64c909.png)
![image](https://user-images.githubusercontent.com/7698511/55387840-c31c1980-5564-11e9-88e8-4a8ef75efa9c.png)
插件安装了，wxss和wxml也重新绑定的，依然报错

**Comment by zxj5470** [comment]
> ![image](https://user-images.githubusercontent.com/7698511/55387813-b7305780-5564-11e9-8232-b01e5f64c909.png)
> ![image](https://user-images.githubusercontent.com/7698511/55387840-c31c1980-5564-11e9-88e8-4a8ef75efa9c.png)
> 插件安装了，wxss和wxml也重新绑定的，依然报错

@liunewshine 这个问题我另开文档或者写到readme里面。alt+enter关掉就行了。

**Comment by zxj5470** [comment]
由于已经上架 JB 插件，关闭本issue
