### ISSUE TITLE
下面这种属性不赋值不应该提示错误

### ISSUE THREAD

**Issue by liunewshine** [zxj5470/wxapp-intellij#10]
![image](https://user-images.githubusercontent.com/7698511/61105032-2c3bf300-a4ab-11e9-9095-71dad7a6ac15.png)

**Comment by zxj5470** [comment]
这是他们xml parser的问题了23333~以后考虑改用自己的parser

**Comment by zxj5470** [comment]
换一种临时的解决方案……直接屏蔽报错信息
