### ISSUE TITLE
更新0.2.7后,会导致其他的项目的vue文件打不开

### ISSUE THREAD

**Issue by liunewshine** [zxj5470/wxapp-intellij#11]
更新0.2.7后,vue项目的很多vue文件无法打开,一直loading.
卸载该插件后可以正常打开,再次安装后依然导致vue文件打不开.
![image](https://user-images.githubusercontent.com/7698511/61230212-359fb680-a75c-11e9-9a2e-8000a494cdc2.png)
![image](https://user-images.githubusercontent.com/7698511/61230216-37697a00-a75c-11e9-807c-436b8a00d3e6.png)

**Comment by liunewshine** [comment]
我手动下载0.2.6安装后,一切正常,说明就是0.2.7的问题

**Comment by zxj5470** [comment]
0.2.6 到 0.2.7 没有修改 plugin.xml 内容，仅修改 wxapp 对191及以上使用高分辨率图标及192兼容API
。
请确认 Vue 插件版本是否为最新……我在macOS和Windows的183和191试了均没有问题……
（在191上有一个CSS的报错但不影响代码格式化rpx使用）

**Comment by hfxchan** [comment]
@zxj5470 同样的问题, 安装插件后会导致 使用mpvue 的项目 vue格式文件打不开, 禁用插件后恢复正常.

**Comment by liunewshine** [comment]
看来不止我一个人这样，不是所有的vue都打不开，只有部分打不开，貌似还和项目有关，有的项目就正常

**Comment by hfxchan** [comment]
> @zxj5470 同样的问题, 安装插件后会导致 使用mpvue 的项目 vue格式文件打不开, 禁用插件后恢复正常. 测试非mpvue的项目, 能正常打开vue文件,
> 
> ![image](https://user-images.githubusercontent.com/5492330/61609963-4e432b80-ac8a-11e9-937a-b8ce35815ec0.png)

发现只要有样式里有伪元素选择器就会打不开, 不单是vue文件, 所有的含有样式的文件都是, 
例如
`.test::after`

**Comment by liunewshine** [comment]
求大神尽快解决这个问题,我手动安装了0.2.8,问题依旧.并且升级到Intellij 2019.2以后,0.2.6无法使用. 现在无解了

**Comment by hu437** [comment]
wxss，css文件都无法打开一下显示loading

**Comment by zxj5470** [comment]
妈的一个个就懂得提问题连复线代码都不贴一下让我自己瞎找，我从来不碰 .vue的。
问题在 Vue 文件这个 style scoped 上
```css
<style scoped>
/* ...... */
</style>
```

**Comment by liunewshine** [comment]
楼上已经找到问题了呀，和vue无关，只要是包含了css伪类，就肯定打不开，不论是css文件还是vue文件或者wss

**Comment by zxj5470** [comment]
好像我知道问题在哪了……是我覆盖了JB的那个CssValue的类

**Comment by zxj5470** [comment]
https://ci.appveyor.com/project/zxj5470/wxapp-intellij/build/artifacts/
