### ISSUE TITLE
跟插件wechat-weapp-support好像有冲突

### ISSUE THREAD

**Issue by copyer1998** [zxj5470/wxapp-intellij#12]
wechat-weapp-support也是小程序插件,这两个同时启用会发现wxss文件打不开

**Comment by zxj5470** [comment]
当然是选我啦（ 

![image](https://user-images.githubusercontent.com/20026798/61591790-45f0df00-abfd-11e9-9b14-5ca6b8d1f3d8.png)
![image](https://user-images.githubusercontent.com/20026798/61591794-53a66480-abfd-11e9-9969-64d04d5f976a.png)
