### ISSUE TITLE
wxss没有代码提示

### ISSUE THREAD

**Issue by Garfielk** [zxj5470/wxapp-intellij#15]
大佬你好，wxss没有css属性的提示，另外也不支持emmet

**Comment by xiang473535976** [comment]
希望布局的xml时    class属性时    自动提示css中写好的class名 方便引用   谢谢

**Comment by zxj5470** [comment]
emmet, 那是什么？

**Comment by Garfielk** [comment]
.wxss文件能高亮显示，但是没有属性的代码提示。
![b](https://user-images.githubusercontent.com/10264863/62434118-e69cde00-b769-11e9-8497-dc66b3d24ec9.png)
![edit](https://user-images.githubusercontent.com/10264863/62434138-f4526380-b769-11e9-8817-182ebedb55ae.png)
请问大佬是我的版本和配置有问题么

**Comment by zxj5470** [comment]
最后再给你一次说人话的机会

**Comment by Garfielk** [comment]
> wxss没有css属性的提示

> 属性（Property）：一些人类可理解的标识符，这些标识符指出你想修改哪一些样式，例如：字体，宽度，背景颜色等。

期望的效果：
![tip2](https://user-images.githubusercontent.com/10264863/62509386-8a0af300-b83d-11e9-8720-a195459e507d.png)

![tip](https://user-images.githubusercontent.com/10264863/62509367-7b244080-b83d-11e9-997c-e93922e4705e.png)

目前是这样：
![notip](https://user-images.githubusercontent.com/10264863/62509392-91320100-b83d-11e9-887b-f77e4e3b5af6.png)
![notip2](https://user-images.githubusercontent.com/10264863/62509395-93945b00-b83d-11e9-9abb-29c7e0ca45c6.png)

**Comment by zxj5470** [comment]
0.2.10 ban'be版本

![image](https://user-images.githubusercontent.com/20026798/62772468-3e24ac00-bad2-11e9-849c-6e92cf02fcbb.png)

**Comment by Garfielk** [comment]
升级到0.2.10后解决，感谢回复
