### ISSUE TITLE
部分html文件解析阻塞BUG

### ISSUE THREAD

**Issue by scotox** [zxj5470/wxapp-intellij#16]
**Describe the bug 描述一下bug**

运行环境：

- IntelliJ IDEA 2018.3.6 (Ultimate Edition)
- JRE: 1.8.0_152-release-1343-b28 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Windows 10 10.0

描述：

1. 打开微信小程序工程项目，本插件的功能正常；
2. 打开其他工程项目时，部分html文件加载阻塞，一直显示`Loading...`状态；
3. 禁用本插件后，该部分html文件就能正常加载显示。

**To Reproduce 如何复现bug**

启用本插件，就会出现此BUG，不能加载html，阻塞在`Loading...`状态；

禁用本插件，就能正常加载html文件，并显示。

经初始验证测试，加入以下代码时，就会出现该阻塞BUG：

> 此代码的目的：给 `docsify.js` 添加自定义样式

```html
<!DOCTYPE html>
<html lang="en">
<head>
......
  <!-- 3. Custom Theme Properties -->
  <style>
    :root {
      /* Reduce the font size */ 
      /* --base-font-size: 14px; */
      --cover-heading-color: #000000
      /* Change the theme color hue (0-360) */
      /* --theme-hue: 325; */
  
      /* Add sidebar navigation bullets */
      /* --sidebar-nav-link-before-content-l1: 'ðŸ˜€'; */
      /* --sidebar-nav-link-before-content-l2: 'ðŸ’©'; */

    }
  </style>
......
</head>
```

**Screenshots 截图**

阻塞BUG时的状态：

![image](https://user-images.githubusercontent.com/48884300/62340503-603a8f00-b512-11e9-805a-72e5f88262fa.png)

禁用本插件后：

![image](https://user-images.githubusercontent.com/48884300/62340826-74cb5700-b513-11e9-883b-13afdb8f3ba0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS/Windows] : Windows 10 10.0
 - IntelliJ Platform Version [e.g. 2019.2]：IntelliJ IDEA 2018.3.6 (Ultimate Edition)
 - Plugin Version [e.g. 0.2.8]：0.2.7

**Comment by zxj5470** [comment]
CSS 问题已解决。0.2.9更新还没通过JB审核……
https://ci.appveyor.com/project/zxj5470/wxapp-intellij/build/artifacts/
