### ISSUE TITLE
一个小问题，对于非.wxss文件的rpx单位格式化

### ISSUE THREAD

**Issue by LunaYJ** [zxj5470/wxapp-intellij#18]
这是个小问题

我的小程序是用 mpvue 开发的
然后由于后缀是.vue 文件 css直接写在.vue 中
所以当我格式化 .vue 文件后
css中的 rpx单位前会自动添加空格
不知道作者有没有办法解决

重申，这是个不怎么影响使用的小问题，如果解决不了就无视吧，关闭此issue就好

**Comment by zxj5470** [comment]
CSS问题无解，官方不提供修改CSS的单位。
Vue 的 css 显然是走 inject language 那一套的。
但是……理论上说如果你能把 Vue 的 inject language 改成 wxss，好像就可以……
我看看

**Comment by zxj5470** [comment]
好吧，无解。html不能直接改CSS的部分……而Vue直接继承于HTML文件……没法对HTML直接动刀改。
我能改wxss文件已经是动了很多黑魔法了……
![image](https://user-images.githubusercontent.com/20026798/62820822-ac35a580-bb9c-11e9-856a-a8f3c7c2416e.png)

**Comment by LunaYJ** [comment]
虽然无解，但是依然感谢！
作者加油！
