### ISSUE TITLE
wx.d.ts中fillRect函数的参数顺序有误，导致jb代码提示错误

### ISSUE THREAD

**Issue by cosloli** [zxj5470/wxapp-intellij#21]
wxapp-intellij/wx.d.ts v0.2.10版 第8312行，fillRect的参数顺序与微信文档定义正好相反，导致jb参数提示错误：
![微信截图_20190914171417](https://user-images.githubusercontent.com/7274196/64906040-7a6fab80-d713-11e9-9ee8-9533f1417062.png)
错误提示：
![微信截图_20190914171653](https://user-images.githubusercontent.com/7274196/64906043-7d6a9c00-d713-11e9-8034-97342a544e09.png)
目前解决方案，手动修改index.d.ts，倒转函数参数顺序：
![微信截图_20190914171916](https://user-images.githubusercontent.com/7274196/64906071-fff35b80-d713-11e9-8535-43ee715883a0.png)
调整后不再报错：
![微信截图_20190914171838](https://user-images.githubusercontent.com/7274196/64906073-0681d300-d714-11e9-92d7-d31181b97d2d.png)
希望可以在插件中修复这个问题~

**Comment by zxj5470** [comment]
那么……应该就是wepy的锅了（滑稽

**Comment by cosloli** [comment]
> 那么……应该就是wepy的锅了（滑稽
> https://github.com/Tencent/wepy/blob/2.0.x/packages/core/types/wx/lib.wx.api.d.ts#L8299-L8308

2333 快给他们提issue

**Comment by cosloli** [comment]
已解决，锅是wepy的
