### ISSUE TITLE
代码提示 translate() 参数顺序错误

### ISSUE THREAD

**Issue by KyleBing** [zxj5470/wxapp-intellij#30]
**Describe the bug or Suggestion 描述一下 bug 或者有什么建议**
`animation.translate(tx, ty)` 这个方法的参数名顺序应该是 `tx` `ty` 而不是 `ty` `tx`，目前是 `animation.translate(ty, tx)`。
还有`animation.translate3d(tx, ty, tz)` 这个方法的参数名顺序也有误，也应该是 xyz 这样的顺序，详见页面截图

**To Reproduce 如何复现bug**
`null`

**Screenshots 截图**
> 编辑器中：

<img width="791" alt="Screen Shot 2020-01-18 at 15 24 58" src="https://user-images.githubusercontent.com/12215982/72660324-3cf39580-3a07-11ea-8853-4b9514a0f93e.png">

> 官方文档： 
<img width="1175" alt="Screen Shot 2020-01-18 at 15 24 22" src="https://user-images.githubusercontent.com/12215982/72660329-598fcd80-3a07-11ea-8f12-378cd334822d.png">

> 插件源文件

<img width="785" alt="Screen Shot 2020-01-18 at 15 24 38" src="https://user-images.githubusercontent.com/12215982/72660333-61e80880-3a07-11ea-804e-3c44fac22cd1.png">

> `translate3d()` 也一样

<img width="1145" alt="Screen Shot 2020-01-18 at 15 26 23" src="https://user-images.githubusercontent.com/12215982/72660341-817f3100-3a07-11ea-979d-117a927a04b6.png">

<img width="779" alt="Screen Shot 2020-01-18 at 15 26 35" src="https://user-images.githubusercontent.com/12215982/72660345-85ab4e80-3a07-11ea-829c-504a95e945da.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS/Windows] :
 - IntelliJ Platform Version [e.g. 2019.2]：
 - Plugin Version [e.g. 0.2.8]：

**Additional context 其他相关信息**
`null`

**Comment by zxj5470** [comment]
这个问题建议到wepy项目看看那个d.ts文件有没有问题
