### ISSUE TITLE
安装之后右键菜单会变卡顿

### ISSUE THREAD

**Issue by renlzrz** [zxj5470/wxapp-intellij#5]
wxml和wxss里面右键会很卡顿 偶尔还会报致命错误

**Comment by zxj5470** [comment]
咦，还真是会卡……最奇怪的是连 json文件也一起卡

**Comment by zxj5470** [comment]
大概发现问题在哪了233333与我无关

**Comment by zxj5470** [comment]
问题应该已解决……是JB的GeneralAction的问题。另外……JB自己的插件都因为这个然后报StackOverflow错23333
