### ISSUE TITLE
webstorm中rpx空格能去掉吗？

### ISSUE THREAD

**Issue by lingruibin** [zxj5470/wxapp-intellij#6]
你好，感谢你的这个插件，为我们的开发带来了极大方便。请问webstorm中rpx空格能去掉吗？除了 使用sed软件将空格格式掉的这个方法外。因为这个方式会生成多个sed文件

**Comment by zxj5470** [comment]
您用过插件吗……

**Comment by lingruibin** [comment]
不好意思。我是用less转的。问题出在less中了。wxss没问题的。

在 2019-06-22 07:53:57，"Hong" <notifications@github.com> 写道：


您用过插件吗……

**Comment by zxj5470** [comment]
笑死……
https://blog.csdn.net/lulitianyu/article/details/83240864
最后发现引用的是我的文章23333
