### ISSUE TITLE
图标占满编辑器了。

### ISSUE THREAD

**Issue by lingruibin** [zxj5470/wxapp-intellij#7]
![image](https://user-images.githubusercontent.com/17694154/60013439-0e038400-96b1-11e9-920f-e4f9ca921e18.png)

**Comment by zxj5470** [comment]
唔……用的一定是古代版本的……（183以前的都算古代版本）

**Comment by lingruibin** [comment]
用的就是2018.3的

**Comment by zxj5470** [comment]
那可能是183没更新小版本……我靠。那我这么更新代码判断183岂不是没用了
